### ISSUE TITLE
Doesn't work with typescript < 4.1

### ISSUE THREAD

**Issue by hedgepigdaniel** [LeetCode-OpenSource/emotion-ts-plugin#310]
Due to at least this change: https://github.com/LeetCode-OpenSource/emotion-ts-plugin/pull/306/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R72

Perhaps its worth noting in the peer dependencies that typescript 4.0/4.1 (haven't tested if 4.0 works) is required?

 ```
Module build failed (from node_modules/ts-loader/index.js):
TypeError: Cannot read property 'createImportClause' of undefined
```

**Comment by Brooooooklyn** [comment]
What version of emotion are you using?

**Comment by hedgepigdaniel** [comment]
10.0.0.28, why?

**Comment by Brooooooklyn** [comment]
1.0 dropped `emotion@10` supported. There were so many breaking changes in `v11`. So please use `v0.x` if you were using `emotion@10`.

**Comment by hedgepigdaniel** [comment]
Right thanks, will do.

So I guess the `peerDependencies` in package.json should be something like:
```
"@emotion/core": "^11.0.0",
"typescript": "~4.0.0", // ~ because typescript does breaking changes with feature releases
```
